const fnCallback = (err, data) => {
    console.log("Error: " + err);
    console.log("Data: ", data);
}
